sudo: false

language: node_js

node_js:
  - 0.10

addons:
  apt:
    sources:
      - mongodb-upstart
    packages:
      - mongodb-org-server

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - export COCO_TRAVIS_TEST=1
  - npm install -g npm@latest

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - "./node_modules/jasmine-node/bin/jasmine-node test/server/ --coffee --captureExceptions"
  - "npm run jasmine"
